### ISSUE TITLE
raising vm_vcpus fails suse builds

### ISSUE THREAD

**Issue by FlorianHeigl** [mrlesmithjr/packer-templates#34]
Hi,

I'm preparing a patch that will clean up some parts of the SUSE builds, since a few of them are broken (some just need new ISO urls, but in 99% the problems are because of facter). This is a huge time sink, so I wanted to speed up the installs. 
I try to raise vm_vcpus in opensuse-server.json, it's mentioned twice, supposedly one setting for the build time and one for the generated VM. I noticed, if I change the value from 1 to any other number, the ```typing boot command``` goes wrong and the VM will sit at ```Booting from local disk``` forever.

If you have any advice, I'd appreciate, otherwise this is going to take many more hours for nothing...

**Comment by FlorianHeigl** [comment]
I might have an idea what happens there: It seems the installer goes more fancy if you have more than 1 core or more RAM. Somehow then the menu selection fails.

**Comment by FlorianHeigl** [comment]
It seems this is an issue with running nested on KVM, too. I just gave VBox 2 vcpus in my little MacBook and there it works flawlessly.
So seems, for mass-building the only save way is to launch one VM per build, or use a baremetal build host. I am grateful for any input.

**Comment by mrlesmithjr** [comment]
@FlorianHeigl I actually do builds on nested as well occasionally and can confirm that your results may vary on various scenarios.

**Comment by mrlesmithjr** [comment]
Also, I've debated on removing the facter dependencies and using more native bash functionality.

**Comment by FlorianHeigl** [comment]
I was thinking about to verify how many of the facter-determined variables are actually used, it seems the shell parts do 90% already. it would seem useful to remove it but I got all SUSE / facter issues sorted by now.
I'm refactoring base.sh to be a bit easier on the eyes, since that was giving me the hardest time.
When you review that, maybe you can keep the "do we need facter" in mind - but also after that it will be easier to remove & thus less urgent.

**Comment by FlorianHeigl** [comment]
Oh, closing this for the moment since you were able to confirm there's unstabilities with nested.
I see the debian builds also use QEMU. I'd like to try the same for SUSE at a later point.
