### ISSUE TITLE
global packer_cache directory

### ISSUE THREAD

**Issue by FlorianHeigl** [mrlesmithjr/packer-templates#35]
Could we also symlink the __packer_cache__ subdirectory to ```../../../packer_cache```?

At least in my case it made sense to have it in a different location, and with a symlink that change can be done more easily.

**Comment by mrlesmithjr** [comment]
@FlorianHeigl This is a very interesting idea. Can you elaborate more on your thoughts around this? I can definitely see where this would be beneficial across the different builds that leverage the same ISO rather than downloading the same ISO each time.
