### ISSUE TITLE
base.sh rework

### ISSUE THREAD

**Issue by FlorianHeigl** [mrlesmithjr/packer-templates#38]
Hi,

could you have a look at this gist?
https://gist.github.com/FlorianHeigl/cd4f36acafab02ee6370b8b75452ed96

* tried to unify & sort things a bit.
* pretends to be naive and uses os_name for all main decisions, I'm aware that that will need some testing.
* there are notes where I found missing paths in the original (i.e. OS version dead or one that will not have any choices made for itself)
* no functional / package changes except for facter in some SLES variants & wiping machine-id whereever applicable

*it seems there are many cases where facter doesn't get involved - at least in this script. i think base.sh can work without (relevant for reproducible builds off ISO since facter is often fetched elsewhere). but since many other scripts also rely on it, the choice is not so easy.*

**Comment by mrlesmithjr** [comment]
@FlorianHeigl I am working on something to replace facter which **SHOULD** simplify our scripts. I'll have something soon for us to test if you are interested.

**Comment by mrlesmithjr** [comment]
Thanks for the effort you have been putting into this over the past day or so!

**Comment by mrlesmithjr** [comment]
@FlorianHeigl [This](https://github.com/mrlesmithjr/packer-templates/tree/remove-facter-dependencies) branch has the updated scripts for not relying on Facter any longer. I have been spot checking and have not found any issues yet. However, I am sure there will be something that pops up.

**Comment by FlorianHeigl** [comment]
Oh damn, that's so much less, can you please put a note in the master's
Readme *last week*?

:-) :-)



Larry Smith Jr. <notifications@github.com> schrieb am Mo., 25. Nov. 2019,
15:48:
