### ISSUE TITLE
SUSE templates: cleanup needs to be extended

### ISSUE THREAD

**Issue by FlorianHeigl** [mrlesmithjr/packer-templates#45]
There's one issue in these with packer builds.

You need to clean up the following file

```
linux:~ # find /var -name "*rand*"
/var/lib/misc/random-seed
/var/lib/systemd/random-seed
```

especially since the first of the two has ugly permissions:

```
linux:~ # find /var -name "*rand*" -ls
 70973    4 -rw-r--r--   1 root     root         4096 Nov 23 23:43 /var/lib/misc/random-seed
 60356    4 -rw-------   1 root     root          512 Dec  2 04:52 /var/lib/systemd/random-seed
```
neither should be on-filesystem while the system is running, but the first one is packed with the image(!)

**Comment by FlorianHeigl** [comment]
(i had inadvertedly run into this in '18 but didn't figure it was a packer leftover, so excuse this very late report)

**Comment by mrlesmithjr** [comment]
@FlorianHeigl How do the changes in the above commit look?
